<h1>Index</h1><br>

<?php
    echo 'chegamos no controller index<br>';

    foreach($this->view->dados as $index => $produto){
        // echo $index . " - " . $valor . '<br>';
        echo 'ID: ' . $produto['id'] .' - '. 'Descrição: ' .$produto['descricao']. ' - ' .'Preço: ' . $produto['preco'];
        echo '<br>';
    }

    echo '<hr><pre>';
    print_r($this->view->dados);
    echo '</pre>';
?>